on:
  workflow_call:
    inputs:
      apply:
        type: boolean
        default: false

jobs:
  tf:
    runs-on: ubuntu-latest
    environment: pro
    timeout-minutes: 10
    permissions:
      id-token: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
          mask-aws-account-id: true

      - name: get terraform config
        working-directory: stack
        run: |
          mkdir -p tfvars
          aws s3 sync s3://${{ secrets.TF_STATE_BUCKET }}/tfvars/ tfvars/

      - name: init
        working-directory: stack
        run: |
          terraform init -backend-config=tfvars/backend-pro.hcl

      - name: plan
        if: ${{ !inputs.apply }}
        working-directory: stack
        run: |
          terraform plan -var-file="tfvars/pro.tfvars"

      - name: apply
        if: ${{ inputs.apply }}
        working-directory: stack
        run: |
          terraform apply -auto-approve -var-file="tfvars/pro.tfvars"
